#!/usr/bin/env python3
"""Generate a standalone Macaulay2 input from the extracted Lane 7 JSON.

The generator translates Python's ``**`` exponent notation to Macaulay2's
``^`` notation.  By default it preserves the rational entries verbatim.  The
optional row scaling multiplies by nonzero rational constants, hence preserves
all determinantal rank loci while producing integral matrix entries that are
usually much faster for exact Groebner-basis calculations.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import re
import sys

_ALLOWED_EXPRESSION = re.compile(r"[A-Za-z0-9_+\-*/^(). ]+\Z")

# Least common multiples of all coefficient denominators in the ten rows of
# collision_residual_matrix_M.json from the hash-pinned v19 Lane 7 packet.
# Multiplying rows by these nonzero integers changes every minor only by a unit.
ROW_DENOMINATOR_LCMS = [
    4374,
    8748,
    4374,
    8748,
    486,
    52488,
    104976,
    104976,
    209952,
    314928,
]


def m2_expression(expression: str) -> str:
    converted = expression.replace("**", "^")
    if _ALLOWED_EXPRESSION.fullmatch(converted) is None:
        raise ValueError(f"unsupported character in polynomial expression: {expression!r}")
    return converted


def m2_matrix(rows: list[list[str]]) -> str:
    if not rows or not rows[0]:
        raise ValueError("matrix must be nonempty")
    width = len(rows[0])
    if any(len(row) != width for row in rows):
        raise ValueError("matrix is ragged")
    rendered_rows = [
        "{" + ", ".join(m2_expression(entry) for entry in row) + "}"
        for row in rows
    ]
    return "matrix {\n  " + ",\n  ".join(rendered_rows) + "\n}"


def scaled_rows(entries: list[list[str]], clear_denominators: bool) -> list[list[str]]:
    if not clear_denominators:
        return entries
    if len(entries) != len(ROW_DENOMINATOR_LCMS):
        raise ValueError("row-denominator table does not match the residual matrix")
    return [
        [f"{scale}*({entry})" for entry in row]
        for scale, row in zip(ROW_DENOMINATOR_LCMS, entries)
    ]


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "source_directory",
        type=Path,
        help="directory containing the extracted Lane 7 JSON files",
    )
    parser.add_argument("output", type=Path)
    parser.add_argument(
        "--characteristic",
        type=int,
        default=0,
        help="0 for QQ; otherwise use ZZ/p",
    )
    parser.add_argument(
        "--with-localizer",
        action="store_true",
        help="adjoin z and define localizerEquation=z*d-1",
    )
    parser.add_argument(
        "--clear-row-denominators",
        action="store_true",
        help="multiply rows by packet-specific denominator LCMs",
    )
    args = parser.parse_args()

    if args.characteristic < 0:
        raise ValueError("characteristic must be nonnegative")

    residual_path = args.source_directory / "collision_residual_matrix_M.json"
    factorization_path = args.source_directory / "Hv10_split_matrix_factorization.json"
    residual = json.loads(residual_path.read_text(encoding="utf-8"))
    factorization = json.loads(factorization_path.read_text(encoding="utf-8"))

    entries = residual.get("entries")
    if not isinstance(entries, list) or len(entries) != 10:
        raise ValueError("expected residual entries to have ten rows")
    if any(not isinstance(row, list) or len(row) != 5 for row in entries):
        raise ValueError("expected residual entries to be a 10 by 5 matrix")

    determinant = factorization.get("d")
    if not isinstance(determinant, str):
        raise ValueError("factorization artifact does not contain determinant d")

    coefficient_ring = "QQ" if args.characteristic == 0 else f"ZZ/{args.characteristic}"
    variables = [f"a{i}" for i in range(7)]
    if args.with_localizer:
        variables.append("z")

    matrix_entries = scaled_rows(entries, args.clear_row_denominators)
    lines = [
        "-- Generated from the hash-checked public Lane 7 source packet.",
        "-- Do not edit this file by hand; edit the generator instead.",
        f"R = {coefficient_ring}[{','.join(variables)}, MonomialOrder => GRevLex];",
        f"d = {m2_expression(determinant)};",
        f"M = {m2_matrix(matrix_entries)};",
        "assert(numrows M == 10 and numcols M == 5);",
    ]
    if args.clear_row_denominators:
        lines.append("-- M has been row-scaled by nonzero constants; rank loci are unchanged.")
    if args.with_localizer:
        lines.append("localizerEquation = z*d - 1;")

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text("\n\n".join(lines) + "\n", encoding="utf-8")
    print(
        f"wrote {args.output} over {coefficient_ring} "
        f"({'with' if args.with_localizer else 'without'} localizer; "
        f"{'cleared' if args.clear_row_denominators else 'verbatim'} rows)"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OSError, ValueError, json.JSONDecodeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        raise SystemExit(2)
