#!/usr/bin/env python3
"""Compute the cubic obstruction for every finite line in the selected plane.

Write the finite projective tangent direction as

    theta(r) = theta_v + r theta_u.

The quadratic Kuranishi class vanishes identically on this plane.  This module
constructs, over Q(r), the cubic tangent-effect matrix E(r) and deterministic
cubic residual b(r).  It computes a primitive polynomial basis of the left
kernel of E(r), then studies the ideal in Q[r] generated by all pairings

    w_i(r)^T b(r).

If those pairings generate the unit ideal, a polynomial Bezout combination of
the left-null vectors has constant nonzero pairing with b(r).  That gives one
exact obstruction certificate valid for every finite algebraic value of r.
If the pairing ideal is proper, its factors are reported as the only possible
exceptional finite slopes; each would still require a specialized rank audit.

The point at infinity theta_u is excluded and is audited separately by
``program5_rank_six_line_formal_arc.py``.
"""
from __future__ import annotations

import argparse
import hashlib
import json
import sys
from pathlib import Path
from typing import Any, Sequence

import sympy as sp
from sympy.polys.matrices import DomainMatrix

from .program5_compression_export import DEFAULT_SOURCE, _q
from .program5_rank_six_schur_model import build_schur_model
from .program5_rank_six_second_order import _flatten


def _digest(expressions: Sequence[sp.Expr]) -> str:
    payload = [str(sp.factor(expression)) for expression in expressions]
    return hashlib.sha256(
        json.dumps(payload, separators=(",", ":")).encode("utf-8")
    ).hexdigest()


def _global_coefficient_denominator(
    expressions: Sequence[sp.Expr],
    variable: sp.Symbol,
) -> int:
    denominator = 1
    for expression in expressions:
        polynomial = sp.Poly(expression, variable, domain=sp.QQ)
        for coefficient in polynomial.all_coeffs():
            denominator = sp.ilcm(
                denominator,
                int(sp.denom(coefficient)),
            )
    return denominator


def _primitive_polynomial_vector(
    vector: sp.Matrix,
    variable: sp.Symbol,
) -> tuple[sp.Matrix, sp.Expr, sp.Expr]:
    fractions = [sp.cancel(value) for value in vector]
    denominator_lcm: sp.Expr = sp.Integer(1)
    for value in fractions:
        denominator_lcm = sp.lcm(
            denominator_lcm,
            sp.denom(value),
        )
    polynomial_entries = [
        sp.Poly(
            sp.cancel(value * denominator_lcm),
            variable,
            domain=sp.QQ,
        ).as_expr()
        for value in fractions
    ]
    nonzero_polynomials = [
        sp.Poly(value, variable, domain=sp.QQ)
        for value in polynomial_entries
        if value != 0
    ]
    if not nonzero_polynomials:
        raise AssertionError("zero left-kernel vector")
    common = nonzero_polynomials[0]
    for polynomial in nonzero_polynomials[1:]:
        common = sp.gcd(common, polynomial)
    common_expression = common.monic().as_expr()
    polynomial_entries = [
        sp.cancel(value / common_expression)
        for value in polynomial_entries
    ]
    coefficient_denominator = _global_coefficient_denominator(
        polynomial_entries,
        variable,
    )
    polynomial_entries = [
        sp.expand(coefficient_denominator * value)
        for value in polynomial_entries
    ]
    integer_coefficients = []
    for value in polynomial_entries:
        integer_coefficients.extend(
            int(coefficient)
            for coefficient in sp.Poly(value, variable, domain=sp.ZZ).all_coeffs()
        )
    content = 0
    for coefficient in integer_coefficients:
        content = sp.igcd(content, abs(coefficient))
    if content > 1:
        polynomial_entries = [
            sp.expand(value / content)
            for value in polynomial_entries
        ]
    first_nonzero = next(value for value in polynomial_entries if value != 0)
    if sp.Poly(first_nonzero, variable, domain=sp.QQ).LC() < 0:
        polynomial_entries = [-value for value in polynomial_entries]
    primitive = sp.Matrix(polynomial_entries)

    primitive_nonzero = [
        sp.Poly(value, variable, domain=sp.QQ)
        for value in primitive
        if value != 0
    ]
    primitive_gcd = primitive_nonzero[0]
    for polynomial in primitive_nonzero[1:]:
        primitive_gcd = sp.gcd(primitive_gcd, polynomial)
    return primitive, sp.factor(denominator_lcm), primitive_gcd.monic().as_expr()


def _bezout_pairing_ideal(
    pairings: Sequence[sp.Expr],
    variable: sp.Symbol,
) -> tuple[sp.Poly, list[sp.Poly]]:
    nonzero = [
        (index, sp.Poly(pairing, variable, domain=sp.QQ))
        for index, pairing in enumerate(pairings)
        if pairing != 0
    ]
    if not nonzero:
        raise AssertionError("every left-null pairing vanished identically")

    first_index, generator = nonzero[0]
    coefficients = [sp.Poly(0, variable, domain=sp.QQ) for _ in pairings]
    coefficients[first_index] = sp.Poly(1, variable, domain=sp.QQ)

    for index, polynomial in nonzero[1:]:
        left_coefficient, right_coefficient, new_generator = sp.gcdex(
            generator,
            polynomial,
        )
        coefficients = [
            left_coefficient * coefficient
            for coefficient in coefficients
        ]
        coefficients[index] += right_coefficient
        generator = new_generator

    if generator.is_zero:
        raise AssertionError("Bezout computation returned the zero generator")
    leading = generator.LC()
    generator = generator.monic()
    coefficients = [coefficient / leading for coefficient in coefficients]
    verification = sum(
        coefficient * sp.Poly(pairing, variable, domain=sp.QQ)
        for coefficient, pairing in zip(coefficients, pairings)
    )
    if verification != generator:
        raise AssertionError("Bezout coefficients do not reproduce the pairing gcd")
    return generator, coefficients


def _witness_coordinates(
    witness: sp.Matrix,
    active_rows: Sequence[int],
    model: Any,
) -> list[dict[str, Any]]:
    coordinates = []
    for local_row, coefficient in enumerate(witness):
        if coefficient == 0:
            continue
        coordinate = model.residual_coordinate(active_rows[local_row])
        coordinates.append(
            {
                **coordinate,
                "coefficient_polynomial": str(sp.factor(coefficient)),
            }
        )
    return coordinates


def analyze_generic_line_obstruction(
    source_path: Path = DEFAULT_SOURCE,
) -> dict[str, Any]:
    model = build_schur_model(source_path)
    r = sp.symbols("r")
    theta = model.theta_v + r * model.theta_u
    theta_block = model.blocks(theta)

    H2 = model.quadratic_forcing(theta_block)
    forcing2 = _flatten(H2)
    residual2 = model.project(forcing2)
    if any(value != 0 for value in residual2):
        raise AssertionError("the selected plane lost second-order compatibility")
    P2 = model.solve_image(H2)

    P2_block = model.blocks(P2)
    cubic_residual = model.project(
        _flatten(model.cubic_forcing(theta_block, P2_block))
    )
    tangent_blocks = [model.blocks(vector) for vector in model.tangent_basis]
    effect_columns = [
        model.project(
            _flatten(model.bilinear_effect(tangent_block, theta_block))
        )
        for tangent_block in tangent_blocks
    ]
    active_rows = sorted(
        {
            row
            for row, value in enumerate(cubic_residual)
            if value != 0
        }
        | {
            row
            for column in effect_columns
            for row, value in enumerate(column)
            if value != 0
        }
    )
    effect_matrix = sp.Matrix(
        [
            [column[row, 0] for column in effect_columns]
            for row in active_rows
        ]
    )
    residual_vector = sp.Matrix(
        [cubic_residual[row, 0] for row in active_rows]
    )

    effect_rank = DomainMatrix.from_Matrix(
        effect_matrix,
        fmt="sparse",
    ).to_field().rank()
    augmented_rank = DomainMatrix.from_Matrix(
        effect_matrix.row_join(residual_vector),
        fmt="sparse",
    ).to_field().rank()
    left_kernel = effect_matrix.T.nullspace()
    if len(left_kernel) != len(active_rows) - effect_rank:
        raise AssertionError("symbolic left-nullity disagrees with rank")
    if not left_kernel:
        raise AssertionError("generic cubic effect matrix has no left kernel")

    primitive_witnesses: list[sp.Matrix] = []
    witness_records: list[dict[str, Any]] = []
    pairings: list[sp.Expr] = []
    for index, rational_witness in enumerate(left_kernel):
        witness, cleared_denominator, coordinate_gcd = (
            _primitive_polynomial_vector(rational_witness, r)
        )
        annihilation = (witness.T * effect_matrix).applyfunc(
            lambda value: sp.factor(sp.cancel(value))
        )
        if any(value != 0 for value in annihilation):
            raise AssertionError(
                f"primitive witness {index} does not annihilate E(r)"
            )
        pairing = sp.factor(
            sp.cancel((witness.T * residual_vector)[0, 0])
        )
        sp.Poly(pairing, r, domain=sp.QQ)
        coordinates = _witness_coordinates(witness, active_rows, model)
        primitive_witnesses.append(witness)
        pairings.append(pairing)
        witness_records.append(
            {
                "index": index,
                "cleared_denominator": str(cleared_denominator),
                "coordinate_gcd": str(sp.factor(coordinate_gcd)),
                "nonzero_count": len(coordinates),
                "sha256": _digest(list(witness)),
                "pairing_with_cubic_residual": str(pairing),
                "pairing_degree": sp.Poly(
                    pairing,
                    r,
                    domain=sp.QQ,
                ).degree(),
                "coordinates": coordinates,
            }
        )

    pairing_generator, bezout_coefficients = _bezout_pairing_ideal(pairings, r)
    combined = sp.zeros(len(active_rows), 1)
    for coefficient, witness in zip(bezout_coefficients, primitive_witnesses):
        combined += coefficient.as_expr() * witness
    combined, combined_denominator, combined_coordinate_gcd = (
        _primitive_polynomial_vector(combined, r)
    )
    combined_annihilation = (combined.T * effect_matrix).applyfunc(
        lambda value: sp.factor(sp.cancel(value))
    )
    if any(value != 0 for value in combined_annihilation):
        raise AssertionError("combined Bezout witness does not annihilate E(r)")
    combined_pairing = sp.factor(
        sp.cancel((combined.T * residual_vector)[0, 0])
    )
    combined_pairing_polynomial = sp.Poly(
        combined_pairing,
        r,
        domain=sp.QQ,
    )
    generator_expression = sp.factor(pairing_generator.as_expr())
    universal = pairing_generator.degree() == 0 and combined_pairing != 0

    factor_records = [
        {
            "polynomial": str(sp.factor(factor.as_expr())),
            "degree": factor.degree(),
            "multiplicity": multiplicity,
        }
        for factor, multiplicity in sp.factor_list(pairing_generator)[1]
    ]
    combined_coordinates = _witness_coordinates(combined, active_rows, model)

    sample_checks = []
    for value in (-3, -2, -1, 0, 1, 2, 3, 4, 5):
        substitution = {r: sp.Rational(value)}
        specialized_matrix = effect_matrix.subs(substitution)
        specialized_residual = residual_vector.subs(substitution)
        specialized_rank = DomainMatrix.from_Matrix(
            specialized_matrix,
            fmt="sparse",
        ).rank()
        specialized_augmented_rank = DomainMatrix.from_Matrix(
            specialized_matrix.row_join(specialized_residual),
            fmt="sparse",
        ).rank()
        specialized_witness = combined.subs(substitution)
        specialized_pairing = sp.factor(combined_pairing.subs(substitution))
        if universal:
            if specialized_witness == sp.zeros(combined.rows, 1):
                raise AssertionError(f"universal witness vanished at r={value}")
            if specialized_pairing == 0:
                raise AssertionError(f"universal pairing vanished at r={value}")
        sample_checks.append(
            {
                "u_over_v": value,
                "effect_rank": specialized_rank,
                "augmented_rank": specialized_augmented_rank,
                "cubic_lift_solvable": (
                    specialized_rank == specialized_augmented_rank
                ),
                "combined_witness_nonzero_count": sum(
                    entry != 0 for entry in specialized_witness
                ),
                "combined_pairing": _q(specialized_pairing),
            }
        )

    return {
        "schema_version": 2,
        "name": "Program 5 symbolic finite-ratio cubic obstruction",
        "source_file": str(source_path),
        "source_sha256": model.source_sha256,
        "parameter": "r=u/v",
        "direction": "theta_v + r*theta_u",
        "ambient_operation_dimension": model.ambient_operation_dimension,
        "rank_six_tangent_dimension": len(model.tangent_basis),
        "second_order_residual_identically_zero": True,
        "compressed_cubic_equation_count": len(active_rows),
        "generic_effect_rank_over_Q(r)": effect_rank,
        "generic_augmented_rank_over_Q(r)": augmented_rank,
        "left_kernel_dimension_over_Q(r)": len(left_kernel),
        "primitive_left_kernel_basis": witness_records,
        "pairing_ideal": {
            "generator": str(generator_expression),
            "degree": pairing_generator.degree(),
            "factorization": factor_records,
            "bezout_coefficients": [
                str(sp.factor(coefficient.as_expr()))
                for coefficient in bezout_coefficients
            ],
        },
        "combined_bezout_certificate": {
            "cleared_denominator": str(combined_denominator),
            "coordinate_gcd": str(sp.factor(combined_coordinate_gcd)),
            "nonzero_count": len(combined_coordinates),
            "sha256": _digest(list(combined)),
            "pairing_with_cubic_residual": str(combined_pairing),
            "pairing_degree": combined_pairing_polynomial.degree(),
            "coordinates": combined_coordinates,
        },
        "universal_obstruction_for_all_finite_algebraic_ratios": universal,
        "sample_checks": sample_checks,
        "interpretation_boundary": (
            "The certificate concerns all finite lines in this selected "
            "second-order-compatible tangent plane. It does not classify "
            "directions outside the plane or the point at infinity theta_u."
        ),
    }


def main(argv: Sequence[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args(argv)
    try:
        result = analyze_generic_line_obstruction(args.source)
    except (OSError, ValueError, TypeError, AssertionError) as exc:
        print(
            f"program5_rank_six_generic_line_obstruction: {exc}",
            file=sys.stderr,
        )
        return 2
    rendered = json.dumps(result, indent=2, sort_keys=True) + "\n"
    if args.output:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    else:
        sys.stdout.write(rendered)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
