#!/usr/bin/env python3
"""Verify the Lane 5 standard-source degree-six fiber certificate.

The script uses only Python's standard library.  It reconstructs rational
split fibers of the displayed Keller map, forms the evaluation-difference
matrix on all source monomials of total degree at most six, checks an 81 x 81
minor modulo a prime, and verifies the exact kernel vectors 1, Q, and R.

A nonzero modular minor is also a nonzero rational minor.  Since every element
of k[P,Q,R] is constant on each displayed fiber pair, the certificate proves
over every characteristic-zero field k that

    k[P,Q,R] intersect k[x,y,z]_{<=6} = span_k{1,Q,R}.

Consequently the algebra generated by the standard degree-six filtered piece
is k[Q,R] and has transcendence degree two.
"""

from __future__ import annotations

import argparse
import json
from fractions import Fraction
from pathlib import Path
from typing import Iterable

HERE = Path(__file__).resolve().parent
CERTIFICATE = HERE / "standard_filtration_certificate.json"


def q(value: object) -> Fraction:
    return value if isinstance(value, Fraction) else Fraction(value)


def monomials_degree_at_most(bound: int) -> list[tuple[int, int, int]]:
    return [
        (i, j, k)
        for i in range(bound + 1)
        for j in range(bound + 1 - i)
        for k in range(bound + 1 - i - j)
    ]


def map_f(point: tuple[Fraction, Fraction, Fraction]) -> tuple[Fraction, Fraction, Fraction]:
    x, y, z = map(q, point)
    a = 1 + x * y
    p = a**3 * z + y**2 * a * (4 + 3 * x * y)
    qq = y + 3 * x * a**2 * z + 3 * x * y**2 * (4 + 3 * x * y)
    r = 2 * x - 3 * x**2 * y - x**3 * z
    return p, qq, r


def inverse_point(
    x: Fraction, p: Fraction, qq: Fraction, r: Fraction
) -> tuple[Fraction, Fraction, Fraction]:
    """Recover a source point from a root x of the inverse cubic."""
    x, p, qq, r = map(q, (x, p, qq, r))
    denominator = x * (4 - 3 * qq * r) - 3 * r
    if x == 0 or denominator == 0:
        raise ZeroDivisionError("inverse chart denominator vanishes")
    t = x * ((qq - 9 * p * r) * x - 2) / denominator
    y = (t - 1) / x
    z = (2 * x - 3 * x * x * y - r) / x**3
    return x, y, z


def split_target(
    a: Fraction, b: Fraction, h: Fraction, sign: int
) -> tuple[
    tuple[Fraction, Fraction, Fraction],
    tuple[
        tuple[Fraction, Fraction, Fraction],
        tuple[Fraction, Fraction, Fraction],
        tuple[Fraction, Fraction, Fraction],
    ],
]:
    """Construct a rational target whose inverse cubic has roots a,b,-a-b."""
    a, b, h = map(q, (a, b, h))
    c = -a - b
    if h == 0 or 0 in (a, b, c) or len({a, b, c}) != 3:
        raise ValueError("roots must be nonzero and distinct")
    s2 = a * b + a * c + b * c
    s3 = a * b * c
    cubic_lead = -h * h
    r = cubic_lead * s3 / 2
    if r == 0:
        raise ValueError("r vanishes")
    qq = (4 - cubic_lead * s2) / (3 * r)
    delta = (a - b) * (a - c) * (b - c)
    linear_coefficient = 16 - 18 * qq * r
    p = (-linear_coefficient + sign * h**3 * delta) / (54 * r**2)

    recovered_lead = (
        27 * p**2 * r**2 - 18 * p * qq * r + 16 * p + qq**3 * r - qq**2
    )
    if recovered_lead != cubic_lead:
        raise AssertionError("target does not have the prescribed inverse cubic")

    target = (p, qq, r)
    points = tuple(inverse_point(root, *target) for root in (a, b, c))
    if any(map_f(point) != target for point in points):
        raise AssertionError("recovered point does not map to the target")
    return target, points  # type: ignore[return-value]


def evaluate_monomials(
    point: tuple[Fraction, Fraction, Fraction],
    monomials: list[tuple[int, int, int]],
    bound: int,
) -> list[Fraction]:
    x, y, z = point
    xp = [Fraction(1)]
    yp = [Fraction(1)]
    zp = [Fraction(1)]
    for _ in range(bound):
        xp.append(xp[-1] * x)
        yp.append(yp[-1] * y)
        zp.append(zp[-1] * z)
    return [xp[i] * yp[j] * zp[k] for i, j, k in monomials]


def row_from_descriptor(
    descriptor: dict[str, object],
    monomials: list[tuple[int, int, int]],
    bound: int,
) -> list[Fraction]:
    _, points = split_target(
        Fraction(str(descriptor["a"])),
        Fraction(str(descriptor["b"])),
        Fraction(str(descriptor["h"])),
        int(descriptor["sign"]),
    )
    pair = int(descriptor["pair"])
    first = evaluate_monomials(points[0], monomials, bound)
    second = evaluate_monomials(points[pair], monomials, bound)
    return [u - v for u, v in zip(first, second)]


def fraction_mod(value: Fraction, prime: int) -> int:
    numerator = value.numerator % prime
    denominator = value.denominator % prime
    if denominator == 0:
        raise ZeroDivisionError("certificate denominator vanishes modulo prime")
    return numerator * pow(denominator, prime - 2, prime) % prime


def rank_and_pivots(matrix: list[list[int]], prime: int) -> tuple[int, list[int]]:
    work = [[entry % prime for entry in row] for row in matrix]
    rows = len(work)
    columns = len(work[0])
    rank = 0
    pivots: list[int] = []
    for column in range(columns):
        pivot_row = next(
            (index for index in range(rank, rows) if work[index][column]), None
        )
        if pivot_row is None:
            continue
        work[rank], work[pivot_row] = work[pivot_row], work[rank]
        inverse = pow(work[rank][column], prime - 2, prime)
        work[rank] = [entry * inverse % prime for entry in work[rank]]
        for index in range(rows):
            if index == rank or not work[index][column]:
                continue
            factor = work[index][column]
            work[index] = [
                (entry - factor * pivot) % prime
                for entry, pivot in zip(work[index], work[rank])
            ]
        pivots.append(column)
        rank += 1
        if rank == rows:
            break
    return rank, pivots


def determinant_mod(matrix: list[list[int]], prime: int) -> int:
    work = [[entry % prime for entry in row] for row in matrix]
    size = len(work)
    determinant = 1
    for column in range(size):
        pivot_row = next(
            (index for index in range(column, size) if work[index][column]), None
        )
        if pivot_row is None:
            return 0
        if pivot_row != column:
            work[column], work[pivot_row] = work[pivot_row], work[column]
            determinant = -determinant
        pivot = work[column][column] % prime
        determinant = determinant * pivot % prime
        inverse = pow(pivot, prime - 2, prime)
        for index in range(column + 1, size):
            if not work[index][column]:
                continue
            factor = work[index][column] * inverse % prime
            for offset in range(column, size):
                work[index][offset] = (
                    work[index][offset] - factor * work[column][offset]
                ) % prime
    return determinant % prime


def dot(left: Iterable[Fraction], right: Iterable[Fraction]) -> Fraction:
    return sum((a * b for a, b in zip(left, right)), Fraction(0))


def kernel_vectors(
    monomials: list[tuple[int, int, int]],
) -> dict[str, list[Fraction]]:
    index = {monomial: position for position, monomial in enumerate(monomials)}
    vectors = {name: [Fraction(0)] * len(monomials) for name in ("1", "Q", "R")}
    vectors["1"][index[(0, 0, 0)]] = 1
    for monomial, coefficient in {
        (0, 1, 0): 1,
        (1, 0, 1): 3,
        (2, 1, 1): 6,
        (3, 2, 1): 3,
        (1, 2, 0): 12,
        (2, 3, 0): 9,
    }.items():
        vectors["Q"][index[monomial]] = coefficient
    for monomial, coefficient in {
        (1, 0, 0): 2,
        (2, 1, 0): -3,
        (3, 0, 1): -1,
    }.items():
        vectors["R"][index[monomial]] = coefficient
    return vectors


def verify(certificate: dict[str, object]) -> dict[str, object]:
    bound = int(certificate["degree_bound"])
    prime = int(certificate["prime"])
    monomials = monomials_degree_at_most(bound)
    expected_monomials = [list(item) for item in monomials]
    if expected_monomials != certificate["monomials"]:
        raise AssertionError("monomial order differs from the certificate")

    descriptors = certificate["selected_rows"]
    if not isinstance(descriptors, list):
        raise TypeError("selected_rows must be a list")
    exact_rows = [
        row_from_descriptor(descriptor, monomials, bound)
        for descriptor in descriptors
    ]
    modular_rows = [
        [fraction_mod(entry, prime) for entry in row] for row in exact_rows
    ]
    rank, pivots = rank_and_pivots(modular_rows, prime)
    expected_pivots = [int(value) for value in certificate["pivot_columns"]]
    if rank != int(certificate["rank"]) or pivots != expected_pivots:
        raise AssertionError("modular rank or pivot columns changed")

    minor = [[row[column] for column in pivots] for row in modular_rows]
    determinant = determinant_mod(minor, prime)
    if determinant != int(certificate["pivot_minor_determinant_mod_prime"]):
        raise AssertionError("pivot minor determinant changed")

    vectors = kernel_vectors(monomials)
    for name, vector in vectors.items():
        if any(dot(row, vector) != 0 for row in exact_rows):
            raise AssertionError(f"{name} is not in the exact rational kernel")

    nonpivots = [
        column for column in range(len(monomials)) if column not in set(pivots)
    ]
    if nonpivots != [int(value) for value in certificate["nonpivot_columns"]]:
        raise AssertionError("nonpivot columns changed")

    return {
        "status": "pass",
        "degree_bound": bound,
        "monomial_count": len(monomials),
        "row_count": len(exact_rows),
        "prime": prime,
        "rank": rank,
        "kernel_dimension": len(monomials) - rank,
        "pivot_minor_determinant_mod_prime": determinant,
        "exact_kernel_vectors_checked": list(vectors),
        "conclusion": certificate["conclusion"],
    }


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--certificate",
        type=Path,
        default=CERTIFICATE,
        help="certificate JSON to verify",
    )
    args = parser.parse_args()
    certificate = json.loads(args.certificate.read_text(encoding="utf-8"))
    result = verify(certificate)
    print(json.dumps(result, indent=2, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
